### ISSUE TITLE
Localisation problems

### ISSUE THREAD

**Issue by vsee** [olieidel/corona-tracker#3]
Hi, thanks for this!

I shared it with some people in the UK and there are some localisation issues.

I am based near Edinburgh and when I open it with a Chrome browser, it shows some bits in German and some in English. For example, the intro text is English but "Abschicken" is German. Also the indicators of single dots on the map are all in German.

Cheers
Volker

**Comment by olieidel** [comment]
Hi Volker!

Good points - those problems still exist right now as there's no straightforward way to include localized strings in (rails) stimulus js controllers. I'll look into it though and, worst case, will resort to English by default.

**Comment by olieidel** [comment]
Defaulting to English for now. Closing :)
